/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/myoperator/poddeployer/pkg/apis/poddeployer/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePoddeployers implements PoddeployerInterface
type FakePoddeployers struct {
	Fake *FakeApiV1alpha1
	ns   string
}

var poddeployersResource = schema.GroupVersionResource{Group: "api.practice.com", Version: "v1alpha1", Resource: "poddeployers"}

var poddeployersKind = schema.GroupVersionKind{Group: "api.practice.com", Version: "v1alpha1", Kind: "Poddeployer"}

// Get takes name of the poddeployer, and returns the corresponding poddeployer object, and an error if there is any.
func (c *FakePoddeployers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Poddeployer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(poddeployersResource, c.ns, name), &v1alpha1.Poddeployer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Poddeployer), err
}

// List takes label and field selectors, and returns the list of Poddeployers that match those selectors.
func (c *FakePoddeployers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PoddeployerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(poddeployersResource, poddeployersKind, c.ns, opts), &v1alpha1.PoddeployerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PoddeployerList{ListMeta: obj.(*v1alpha1.PoddeployerList).ListMeta}
	for _, item := range obj.(*v1alpha1.PoddeployerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested poddeployers.
func (c *FakePoddeployers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(poddeployersResource, c.ns, opts))

}

// Create takes the representation of a poddeployer and creates it.  Returns the server's representation of the poddeployer, and an error, if there is any.
func (c *FakePoddeployers) Create(ctx context.Context, poddeployer *v1alpha1.Poddeployer, opts v1.CreateOptions) (result *v1alpha1.Poddeployer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(poddeployersResource, c.ns, poddeployer), &v1alpha1.Poddeployer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Poddeployer), err
}

// Update takes the representation of a poddeployer and updates it. Returns the server's representation of the poddeployer, and an error, if there is any.
func (c *FakePoddeployers) Update(ctx context.Context, poddeployer *v1alpha1.Poddeployer, opts v1.UpdateOptions) (result *v1alpha1.Poddeployer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(poddeployersResource, c.ns, poddeployer), &v1alpha1.Poddeployer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Poddeployer), err
}

// Delete takes name of the poddeployer and deletes it. Returns an error if one occurs.
func (c *FakePoddeployers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(poddeployersResource, c.ns, name), &v1alpha1.Poddeployer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePoddeployers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(poddeployersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PoddeployerList{})
	return err
}

// Patch applies the patch and returns the patched poddeployer.
func (c *FakePoddeployers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Poddeployer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(poddeployersResource, c.ns, name, pt, data, subresources...), &v1alpha1.Poddeployer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Poddeployer), err
}
