/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/myoperator/poddeployer/pkg/apis/poddeployer/v1alpha1"
	scheme "github.com/myoperator/poddeployer/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PoddeployersGetter has a method to return a PoddeployerInterface.
// A group's client should implement this interface.
type PoddeployersGetter interface {
	Poddeployers(namespace string) PoddeployerInterface
}

// PoddeployerInterface has methods to work with Poddeployer resources.
type PoddeployerInterface interface {
	Create(ctx context.Context, poddeployer *v1alpha1.Poddeployer, opts v1.CreateOptions) (*v1alpha1.Poddeployer, error)
	Update(ctx context.Context, poddeployer *v1alpha1.Poddeployer, opts v1.UpdateOptions) (*v1alpha1.Poddeployer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Poddeployer, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PoddeployerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Poddeployer, err error)
	PoddeployerExpansion
}

// poddeployers implements PoddeployerInterface
type poddeployers struct {
	client rest.Interface
	ns     string
}

// newPoddeployers returns a Poddeployers
func newPoddeployers(c *ApiV1alpha1Client, namespace string) *poddeployers {
	return &poddeployers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the poddeployer, and returns the corresponding poddeployer object, and an error if there is any.
func (c *poddeployers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Poddeployer, err error) {
	result = &v1alpha1.Poddeployer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("poddeployers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Poddeployers that match those selectors.
func (c *poddeployers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PoddeployerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PoddeployerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("poddeployers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested poddeployers.
func (c *poddeployers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("poddeployers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a poddeployer and creates it.  Returns the server's representation of the poddeployer, and an error, if there is any.
func (c *poddeployers) Create(ctx context.Context, poddeployer *v1alpha1.Poddeployer, opts v1.CreateOptions) (result *v1alpha1.Poddeployer, err error) {
	result = &v1alpha1.Poddeployer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("poddeployers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(poddeployer).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a poddeployer and updates it. Returns the server's representation of the poddeployer, and an error, if there is any.
func (c *poddeployers) Update(ctx context.Context, poddeployer *v1alpha1.Poddeployer, opts v1.UpdateOptions) (result *v1alpha1.Poddeployer, err error) {
	result = &v1alpha1.Poddeployer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("poddeployers").
		Name(poddeployer.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(poddeployer).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the poddeployer and deletes it. Returns an error if one occurs.
func (c *poddeployers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("poddeployers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *poddeployers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("poddeployers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched poddeployer.
func (c *poddeployers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Poddeployer, err error) {
	result = &v1alpha1.Poddeployer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("poddeployers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
