apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypoddeployer-controller
  namespace: default
spec:
  selector:
    matchLabels:
      app: mypoddeployer-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: mypoddeployer-controller
    spec:
      nodeName: vm-0-16-centos # 只调度到这个节点上
      serviceAccountName: mypoddeployer-sa # 配置service account
      containers:
        - name: mypoddeployer
          image: alpine:3.12
          imagePullPolicy: IfNotPresent
          env:
            - name: "Release"
              value: "1"
          workingDir: "/app"
          command: ["./mypoddeployeroperator"]
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mypoddeployer-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8888
      nodePort: 31130
  selector:
    app: mypoddeployer-controller
---