apiVersion: api.practice.com/v1alpha1
kind: Poddeployer
metadata:
  name: mypoddeployer
  namespace: default
spec:
  deployment_spec:
    replicas: 1
    template:
      spec:
        containers:
          - name: example1
            image: busybox:1.34
            command:
              - "sleep"
              - "3600"
          - name: example2
            image: nginx:1.14.2
            ports:
            - containerPort: 80
          - name: example3
            image: nginx:1.14.2
            ports:
            - containerPort: 81
          - name: example4
            image: nginx:1.18-alpine
            ports:
              - containerPort: 82
  priority_images: # image的权重排序
    - image: example1
      value: 200
    - image: example2
      value: 50
    - image: example3
      value: 100
    - image: example4
      value: 1000






