apiVersion: api.practice.com/v1alpha1
kind: Poddeployer
metadata:
  name: mypoddeployer
  namespace: default
spec:
  deployment_spec:
    replicas: 1
    template:
      spec:
        containers:
          - name: example1
            image: busybox:1.34
            command:
              - "sleep"
              - "3600"
          - name: example2
            image: nginx:1.14.2
            ports:
            - containerPort: 80
  priority_images:
    - image: example1
      value: 200
    - image: example2
      value: 50






