apiVersion: api.practice.com/v1alpha1
kind: Poddeployer
metadata:
  name: mypoddeployer-daemonsets
  namespace: default
spec:
  type: apps/v1/daemonsets
  daemonset_spec:
    replicas: 3
    selector:
      matchLabels:
        app: myapp-pod
    template:
      metadata:
        labels:
          app: myapp-pod
      spec:
        containers:
          - name: example1
            image: busybox:1.34
            command:
              - "sleep"
              - "3600"
          - name: example2
            image: nginx:1.18-alpine
            ports:
              - containerPort: 80
  priority_images: # image的权重排序
    - image: example1
      value: 200
    - image: example2
      value: 50







